name: Release firmware

on:
  workflow_run:
    types:
      - "completed"
    workflows:
      - "Build firmware"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'

      - name: Install dependencies
        run: npm i

      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: ${{ github.actor }}

      - name: Semantic Release
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
